import { Platform } from "react-native";

export {
  OS_ANDROID_HEIGHT,
  OS_IOS_HEIGHT,
  OS_HEIGHT,
  TEXT_SIZE_SMALL,
  TEXT_SIZE_MEDIUM,
  TEXT_SIZE_LARGE,
  TEXT_SIZE_XLARGE,
  ICON_SIZE_XLARGE as ICON_SIZE_XLARGE,
  ICON_SIZE_LARGE as ICON_SIZE_MEDIUM,
  ICON_SIZE_MEDIUM as ICON_SIZE_SMALL,
  ICON_SIZE_XSMALL as ICON_SIZE_XSMALL,
  ICON_SIZE_SMALLL as ICON_SIZE_BUTTON,
  DRAWER_HEIGHT,
  RADIUS_BUTTON,
  PADDING_EXTRA_SMALL,
  PADDING_SMALL,
  PADDING_MEDIUM,
  PADDING_LARGE,
};

// OS Height
const OS_ANDROID_HEIGHT = 115
const OS_IOS_HEIGHT = 65
const OS_HEIGHT = Platform.OS === "ios" ? OS_IOS_HEIGHT : OS_ANDROID_HEIGHT

// Text Size
const TEXT_SIZE_SMALL = 12;
const TEXT_SIZE_MEDIUM = 14;
const TEXT_SIZE_LARGE = 16;
const TEXT_SIZE_XLARGE = 18;

// Icon Size
const ICON_SIZE_XSMALL = 10
const ICON_SIZE_SMALLL = 14
const ICON_SIZE_MEDIUM = 18;
const ICON_SIZE_LARGE = 22;
const ICON_SIZE_XLARGE = 26;

// Drawer Height
const DRAWER_HEIGHT = 500; // tinggi drawer5

// Radius Button
const RADIUS_BUTTON = 50

// Padding
const PADDING_EXTRA_SMALL = 10
const PADDING_SMALL = 12
const PADDING_MEDIUM = 16
const PADDING_LARGE = 20

