export {
  TEXT_SIZE_SMALL,
  TEXT_SIZE_MEDIUM,
  TEXT_SIZE_LARGE,
  ICON_SIZE_SMALL,
  ICON_SIZE_MEDIUM,
  DRAWER_HEIGHT,
  RADIUS_BUTTON,
};

const TEXT_SIZE_SMALL = 12;
const TEXT_SIZE_MEDIUM = 14;
const TEXT_SIZE_LARGE = 16;
const ICON_SIZE_SMALL = 20;
const ICON_SIZE_MEDIUM = 24;
const DRAWER_HEIGHT = 500; // tinggi drawer5
const RADIUS_BUTTON = 50