export const jobDataDummy = [
  {
    id: 1,
    posisi: "Front-End Developer",
    perusahaan: "PT Teknologi Hebat",
    lokasi: "Jakarta",
    deskripsi: "Membangun UI dengan React.js",
    tanggalDibuka: "2025-07-25",
  },
  {
    id: 2,
    posisi: "Back-End Developer",
    perusahaan: "PT Solusi Digital",
    lokasi: "Bandung",
    deskripsi: "REST API dengan Node.js & Express",
    tanggalDibuka: "2025-07-20",
  },
  {
    id: 3,
    posisi: "UI/UX Designer",
    perusahaan: "StartupKita",
    lokasi: "Yogyakarta",
    deskripsi: "Desain aplikasi mobile dengan Figma",
    tanggalDibuka: "2025-07-15",
  },
  {
    id: 4,
    posisi: "DevOps Engineer",
    perusahaan: "Cloudify Indonesia",
    lokasi: "Remote",
    deskripsi: "Automasi CI/CD pipeline di AWS",
    tanggalDibuka: "2025-07-22",
  },
  {
    id: 5,
    posisi: "Mobile Developer",
    perusahaan: "AppMaju",
    lokasi: "Surabaya",
    deskripsi: "Kembangkan aplikasi Flutter",
    tanggalDibuka: "2025-07-10",
  },
  {
    id: 6,
    posisi: "Data Analyst",
    perusahaan: "InsightData",
    lokasi: "Jakarta",
    deskripsi: "Visualisasi data & dashboard BI",
    tanggalDibuka: "2025-07-18",
  },
  {
    id: 7,
    posisi: "Machine Learning Engineer",
    perusahaan: "AIWorks",
    lokasi: "Bandung",
    deskripsi: "Model prediktif dengan Python & TensorFlow",
    tanggalDibuka: "2025-07-05",
  },
  {
    id: 8,
    posisi: "System Administrator",
    perusahaan: "NetSecure",
    lokasi: "Depok",
    deskripsi: "Maintain server Linux & firewall",
    tanggalDibuka: "2025-07-08",
  },
  {
    id: 9,
    posisi: "Quality Assurance",
    perusahaan: "TechTesters",
    lokasi: "Semarang",
    deskripsi: "Manual & automated testing",
    tanggalDibuka: "2025-07-12",
  },
  {
    id: 10,
    posisi: "Product Manager",
    perusahaan: "Inovasi Digital",
    lokasi: "Remote",
    deskripsi: "Riset, roadmap, dan koordinasi tim dev",
    tanggalDibuka: "2025-07-01",
  },
];
